MODULE_NAME = "polls"
CALLBACK_PREFIX = "polls:"

STORE_EVENTS = True
STORE_UNKNOWN_POLLS = False
DEFAULT_ANONYMOUS = False
UNKNOWN_POLL_RETRY_SEC = 30
UNKNOWN_POLL_RETRY_STEP_SEC = 1
REJECT_ANSWERS_FROM_BANNED = False

MIN_POLL_OPTIONS = 2
MAX_POLL_OPTIONS = 10
MAX_POLL_QUESTION_LEN = 300
MAX_POLL_OPTION_LEN = 100
RECENT_POLLS_LIMIT = 10
